name: Deploy do site "cep.exkyn.com.br" em homologação

on:
  push:
    branches: [ "approval" ]
  pull_request:
    branches: [ "approval" ]

env:
  LOCAL: ${{ github.workspace }}/output/
  SERVER: "hmg.exkyn.com.br/"
  SERVER_IP: "50.114.32.175"
  POOL: "hmg.exkyn.com.br"
  
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Obtem o código
      uses: actions/checkout@v4

    - name: Configura o .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restaura as Dependencias
      run: dotnet restore
      
    - name: Gera o Pacote
      run: dotnet publish --no-self-contained -r win-x64 -c release -o ${{ env.LOCAL }}

    - name: Parar o pool do IIS
      uses: im-open/app-pool-action@v2.0.4
      with:
        action: 'stop'
        server: ${{ env.SERVER_IP }}
        app-pool-name: ${{ env.POOL }}
        service-account-id: ${{ secrets.USER_SERVER }}
        service-account-password: ${{ secrets.PASSWORD_SERVER }}

    - name: Publica os Arquivos
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST_FTP }}
        username: ${{ secrets.USER_FTP }}
        password: ${{ secrets.PASSWORD_FTP }}
        local-dir: ${{ env.LOCAL }}
        server-dir: ${{ env.SERVER }}
